language: android
android:
  components:
    - platform-tools
    - tools
  licenses:
    - 'android-sdk-license-.+'

before_script:
    - echo yes | android update sdk -u -a -t tools
    - echo yes | android update sdk -u -a -t build-tools-20.0.0,build-tools-19.1.0
    - echo yes | android update sdk -u -a -t android-20,android-19
    - echo yes | android update sdk -u -a -t extra-google-m2repository
    - echo yes | android update sdk -u -a -t extra-android-m2repository
    - echo yes | android update sdk -u -a -t extra-android-support,extra-google-google_play_services

script: ./gradlew build

deploy:
  provider: releases
  api_key:
    secure: N1sRQjwlExc51dA10dOvzdnkYMh9/X9WZmKwYqnWOguV+0dg3Jw2xXyBRxZLO1olIlIV0XGaI1HLAAO0OaFEYyWMO9BkZ60aJC8gePGnnwk1LSYR2moGAtlF6Y+aumfMZzXG4gU4QlVKbMd0uLvUWKu6eTqoMtVe+/C8GeJn6pk=
  file: "./Android/build/outputs/apk/Android-release-unsigned.apk"
  skip_cleanup: true
  on:
    tags: true
    branch: feature_travis_ci
